'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class CLIENTE
    Public Property cedulaPK As String
    Public Property tel As String
    Public Property nombre As String
    Public Property primerApellido As String
    Public Property segundoApellido As String
    Public Property correo As String
    Public Property distrito As String
    Public Property canton As String
    Public Property provincia As String
    Public Property direccionExacta As String

    Public Overridable Property PROYECTOes As ICollection(Of PROYECTO) = New HashSet(Of PROYECTO)

End Class
