'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class EMPLEADO
    Public Property cedulaPK As String
    Public Property tel As String
    Public Property nombre As String
    Public Property primerApellido As String
    Public Property segundoApellido As String
    Public Property correo As String
    Public Property distrito As String
    Public Property canton As String
    Public Property provincia As String
    Public Property direccionExacta As String
    Public Property horasLaboradas As Nullable(Of Integer)
    Public Property edad As Integer
    Public Property disponibilidad As Nullable(Of Boolean)
    Public Property rol As String
    Public Property fechaNacimiento As Date

    Public Overridable Property HABILIDADES As ICollection(Of HABILIDADE) = New HashSet(Of HABILIDADE)
    Public Overridable Property PARTICIPAs As ICollection(Of PARTICIPA) = New HashSet(Of PARTICIPA)

End Class
