'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class HABILIDADE
    Public Property valorPK As String
    Public Property tipoPK As String
    Public Property cedulaEmpleadoFK As String

    Public Overridable Property EMPLEADO As EMPLEADO

End Class
