'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class PARTICIPA
    Public Property rol As String
    Public Property cedulaEmpleadoFK As String
    Public Property idProyectoFK As String

    Public Overridable Property EMPLEADO As EMPLEADO
    Public Overridable Property PROYECTO As PROYECTO

End Class
