'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class PROYECTO
    Public Property idPK As String
    Public Property nombre As String
    Public Property objetivo As String
    Public Property duracionReal As Nullable(Of Integer)
    Public Property duracionEstimada As Nullable(Of Integer)
    Public Property fechaInicio As Nullable(Of Date)
    Public Property fechaFinalizacion As Nullable(Of Date)
    Public Property estado As String
    Public Property cedulaClienteFK As String

    Public Overridable Property CLIENTE As CLIENTE
    Public Overridable Property PARTICIPAs As ICollection(Of PARTICIPA) = New HashSet(Of PARTICIPA)

End Class
