//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PI_INGE_BASES.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HABILIDADES
    {
        public string valorPK { get; set; }
        public string tipoPK { get; set; }
        public string cedulaEmpleadoFK { get; set; }
    
        public virtual EMPLEADO EMPLEADO { get; set; }
    }
}
