//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------
using System.ComponentModel.DataAnnotations;

namespace ProyectoPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PARTICIPA
    {
        public string rol { get; set; }
        public string cedulaEmpleadoFK { get; set; }
        public string idProyectoFK { get; set; }
    
        public virtual EMPLEADO EMPLEADO { get; set; }
        public virtual PROYECTO PROYECTO { get; set; }
    }

    public  class TeamViewModel
    {
        public TeamViewModel ()
        {

        }
        [Display(Name = "ID Proyecto")]
        public string id { get; set;}
        [Display(Name = "Nombre Completo")]
        public string employee { get; set; }
        [Display(Name = "Numero de Contacto")]
        public string email { get; set; }
        [Display(Name = "Rol")]
        public string role { get; set; }
        [Display(Name = "Nombre de Proyecto")]
        public string proyName { get; set; }
    }
}
