//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PARTICIPA
    {
        public string rol { get; set; }
        public string cedulaEmpleadoFK { get; set; }
        public string idProyectoFK { get; set; }
    
        public virtual EMPLEADO EMPLEADO { get; set; }
        public virtual PROYECTO PROYECTO { get; set; }
    }

    public class teamViewModel
    {
        public string Name_Emp { get; set; }
        public string ContactNum { get; set; }
    }
}
