//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class REQUERIMIENTOS
    {
        public string idFK { get; set; }
        public string nombrePK { get; set; }
        public System.DateTime fechaInicio { get; set; }
        public System.DateTime fechaEntrega { get; set; }
        public Nullable<System.TimeSpan> horasReales { get; set; }
        public System.TimeSpan horasEstimadas { get; set; }
        public string dificultad { get; set; }
        public string cedulaFK { get; set; }
    
        public virtual EMPLEADO EMPLEADO { get; set; }
        public virtual PROYECTO PROYECTO { get; set; }
    }
}
